inherit_from:
  # - https://relaxed.ruby.style/rubocop.yml
  - .rubocop-https---relaxed-ruby-style-rubocop-yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - spec/rb27/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
