inherit_from:
  - https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
