inherit_from:
  # - https://relaxed.ruby.style/rubocop.yml
  - .rubocop-https---relaxed-ruby-style-rubocop-yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/rb27/*

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - teckel.gemspec
    - spec/**/*_spec.rb

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Gemspec/OrderedDependencies:
  Enabled: false
